export const nutritionUniversities = [
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Atatürk Üniversitesi",
  "Avrasya Üniversitesi",
  "Aydın Adnan Menderes Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Baskent Üniversitesi",
  "Bayburt Üniversitesi",
  "Bezmialem Vakıf Üniversitesi",
  "Bingöl Üniversitesi",
  "Biruni Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Demiroğlu Bilim Üniversitesi",
  "Doğu Akdeniz Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Fırat Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
  "Girne Amerikan Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Haliç Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Iğdır Üniversitesi",
  "Isparta Uygulamalı Bilimler Üniversitesi",
  "İhsan Doğramacı Bilkent Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Galata Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Sağlık ve Teknoloji Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Yeni Yüzyıl Üniversitesi",
  "İstinye Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Katip Çelebi Üniversitesi",
  "İzmir Tınaztepe Üniversitesi",
  "Kapadokya Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "KTO Karatay Üniversitesi",
  "Lefke Avrupa Üniversitesi",
  "Lokman Hekim Üniversitesi",
  "Marmara Üniversitesi",
  "Mersin Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Nuh Naci Yazgan Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Pamukkale Üniversitesi",
  "Sanko Üniversitesi",
  "Sağlık Bilimleri Üniversitesi",
  "Selçuk Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Tarsus Üniversitesi",
  "Tekirdağ Namık Kemal Üniversitesi",
  "Toros Üniversitesi",
  "Trakya Üniversitesi",
  "Ufuk Üniversitesi",
  "Uşak Üniversitesi",
  "Üsküdar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Yüksekihtisas Üniversitesi",
  "Yakın Doğu Üniversitesi"
].sort();
